install: 
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

services: 
  - postgresql  

script:
  - rails db:create 
  - rails db:migrate
  - rails db:environment:set RAILS_ENV=test 
  - rails webpacker:compile
  - rspec
